import { AdminGuard } from "@/components/admin-guard";
import { MarketplaceNotificationCenterPanel } from "@/components/marketplace-notification-center-panel";
import { MarketplacePageShell } from "@/components/marketplace-page-shell";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default function MarketplaceNotificationsPage() {
  return (
    <AdminGuard>
      <MarketplacePageShell
        title="Notification Center"
        subtitle="Review matching leads generated by your saved searches and clear alerts as you work through them."
        activeTab="notifications"
      >
        <MarketplaceNotificationCenterPanel />
      </MarketplacePageShell>
    </AdminGuard>
  );
}
