import "server-only";

export type AiGenerationRequest = {
  employeeSlug: string;
  systemPrompt: string;
  userPrompt: string;
  context: Record<string, string>;
};

export type AiGenerationResult = {
  content: string;
  provider: string;
  model: string;
  isMock: boolean;
};

export type AiProviderErrorDetails = {
  provider: string;
  model: string;
  status: number;
  code: string | null;
  type: string | null;
  message: string;
};

export class AiProviderError extends Error {
  readonly details: AiProviderErrorDetails;

  constructor(details: AiProviderErrorDetails) {
    super(`${details.provider} request failed with status ${details.status}.`);
    this.name = "AiProviderError";
    this.details = details;
  }
}

export interface AiProvider {
  generate(input: AiGenerationRequest): Promise<AiGenerationResult>;
}

function readModelName() {
  return process.env.AI_MODEL?.trim() || "default";
}

function sanitizeProviderMessage(message: string) {
  return message
    .replace(/sk-[A-Za-z0-9_-]+/g, "[REDACTED_API_KEY]")
    .replace(/Bearer\s+[A-Za-z0-9._-]+/gi, "Bearer [REDACTED_TOKEN]")
    .trim();
}

async function parseProviderError(response: Response) {
  const rawBody = await response.text();
  let message = `Provider returned HTTP ${response.status}.`;
  let code: string | null = null;
  let type: string | null = null;

  try {
    const parsed = JSON.parse(rawBody) as {
      error?: {
        message?: string;
        code?: string;
        type?: string;
      };
    };

    if (parsed.error?.message) {
      message = parsed.error.message;
    }

    code = parsed.error?.code ?? null;
    type = parsed.error?.type ?? null;
  } catch {
    if (rawBody.trim().length > 0) {
      message = rawBody.slice(0, 300);
    }
  }

  return {
    message: sanitizeProviderMessage(message),
    code,
    type,
  };
}

class MockAiProvider implements AiProvider {
  async generate(input: AiGenerationRequest): Promise<AiGenerationResult> {
    const contextSummary = Object.entries(input.context)
      .filter(([, value]) => value.trim().length > 0)
      .map(([key, value]) => `- ${key}: ${value}`)
      .join("\n");

    return {
      content: [
        "Development response only.",
        "No provider key is configured, so this output is generated by the safe mock provider.",
        "",
        `Employee: ${input.employeeSlug}`,
        `Prompt: ${input.userPrompt}`,
        contextSummary ? "" : "No structured context supplied.",
        contextSummary,
        "",
        "Suggested draft:",
        "1. Clarify objective",
        "2. Produce first draft",
        "3. Send for human approval",
      ]
        .filter(Boolean)
        .join("\n"),
      provider: "mock",
      model: "mock-v1",
      isMock: true,
    };
  }
}

class OpenAiProvider implements AiProvider {
  constructor(private readonly apiKey: string) {}

  async generate(input: AiGenerationRequest): Promise<AiGenerationResult> {
    const model = readModelName();

    const response = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model,
        input: [
          {
            role: "system",
            content: input.systemPrompt,
          },
          {
            role: "user",
            content: `${input.userPrompt}\n\nContext:\n${JSON.stringify(input.context, null, 2)}`,
          },
        ],
      }),
    });

    if (!response.ok) {
      const providerError = await parseProviderError(response);
      throw new AiProviderError({
        provider: "openai",
        model,
        status: response.status,
        code: providerError.code,
        type: providerError.type,
        message: providerError.message,
      });
    }

    const payload = (await response.json()) as {
      output_text?: string;
      output?: Array<{
        type?: string;
        content?: Array<{
          type?: string;
          text?: string;
        }>;
      }>;
    };

    const extractedText =
      payload.output_text?.trim() ||
      payload.output
        ?.flatMap((item) => item.content ?? [])
        .filter((item) => item.type === "output_text")
        .map((item) => item.text?.trim() ?? "")
        .filter(Boolean)
        .join("\n\n") ||
      "No content returned.";

    return {
      content: extractedText,
      provider: "openai",
      model,
      isMock: false,
    };
  }
}

class AnthropicProvider implements AiProvider {
  constructor(private readonly apiKey: string) {}

  async generate(input: AiGenerationRequest): Promise<AiGenerationResult> {
    const model = readModelName();

    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model,
        max_tokens: 1200,
        system: input.systemPrompt,
        messages: [
          {
            role: "user",
            content: `${input.userPrompt}\n\nContext:\n${JSON.stringify(input.context, null, 2)}`,
          },
        ],
      }),
    });

    if (!response.ok) {
      const providerError = await parseProviderError(response);
      throw new AiProviderError({
        provider: "anthropic",
        model,
        status: response.status,
        code: providerError.code,
        type: providerError.type,
        message: providerError.message,
      });
    }

    const payload = (await response.json()) as {
      content?: Array<{ type: string; text?: string }>;
    };

    const text =
      payload.content?.find((item) => item.type === "text")?.text ??
      "No content returned.";

    return {
      content: text,
      provider: "anthropic",
      model,
      isMock: false,
    };
  }
}

export function getAiProvider(): AiProvider {
  const providerName = process.env.AI_PROVIDER?.trim().toLowerCase();

  if (providerName === "openai" && process.env.OPENAI_API_KEY) {
    return new OpenAiProvider(process.env.OPENAI_API_KEY);
  }

  if (providerName === "anthropic" && process.env.ANTHROPIC_API_KEY) {
    return new AnthropicProvider(process.env.ANTHROPIC_API_KEY);
  }

  return new MockAiProvider();
}
